# Generated by Django 5.1.6 on 2025-02-11 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationlog',
            name='moderator',
            field=models.ForeignKey(db_column='moderator_id', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.category'),
        ),
        migrations.AddField(
            model_name='problem',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='problem',
            field=models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.problem'),
        ),
        migrations.AddField(
            model_name='moderationlog',
            name='problem',
            field=models.ForeignKey(db_column='problem_id', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='reports.problem'),
        ),
    ]
