# Generated by Django 5.1.6 on 2025-02-24 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Topic',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
