# Generated by Django 5.1.6 on 2025-02-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_category_topic_alter_topic_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='name',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='title',
            field=models.CharField(default='Тема 1', error_messages={'blank': 'Поле не может быть пустым.'}, max_length=100),
        ),
        migrations.AlterModelTable(
            name='topic',
            table=None,
        ),
    ]
