# Generated by Django 5.1.6 on 2025-02-25 15:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_topic_name_topic_description_topic_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem',
            new_name='Report',
        ),
    ]
