# Generated by Django 5.1.6 on 2025-03-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_comment_image_commentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentimage',
            name='image_name',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
