# Generated by Django 5.1.6 on 2025-03-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_commentimage_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='category_text',
        ),
        migrations.RemoveField(
            model_name='report',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('in_moderation', 'На модерации'), ('new', 'Новая'), ('in_progress', 'В обработке'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='in_moderation', max_length=50, null=True),
        ),
    ]
