# Generated by Django 5.1.6 on 2025-03-05 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_comment_options_alter_commentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_reports', models.IntegerField(default=0)),
                ('processed_reports', models.IntegerField(default=0)),
                ('closed_reports', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('in_moderation', 'На модерации'), ('approved', 'Одобрена'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('rejected', 'Отклонена')], default='in_moderation', max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
