# Generated by Django 5.1.6 on 2025-03-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_reportgeneration_alter_report_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgeneration',
            name='avg_time_per_status',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='category_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='reportgeneration',
            name='status_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
