# Generated by Django 5.1.6 on 2025-03-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_reportgeneration_avg_time_per_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportGeneration',
        ),
    ]
